import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { Scores, BallsRemaining, NextBall, Results } from '../components'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        <Scores />
        <BallsRemaining />
        <NextBall />
        <Results />
      </div>
    </>
  )
}

export default Home
