import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { whatIsNeeded } from '../utils'

const Home: NextPage = () => {

  const scorePlayerOne = 0
  const scorePlayerTwo = 140
  const isActivePlayerOne = true
  const numReds = 7
  const numColors = 6
  const nextIsFreeBall = false
  const nextIsColorAfterRed = true

  const playerOneToWin = whatIsNeeded(scorePlayerOne, scorePlayerTwo, numReds, numColors, isActivePlayerOne, nextIsFreeBall, nextIsColorAfterRed)
  const playerTwoToWin = whatIsNeeded(scorePlayerTwo, scorePlayerOne, numReds, numColors, !isActivePlayerOne, nextIsFreeBall, nextIsColorAfterRed)

  return (

    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>Player One</div>
      <div>{playerOneToWin.steps}</div>
      <div>{`${playerOneToWin.winnerScore} - ${playerOneToWin.loserScore}`}</div>
      <div>{`${playerOneToWin.winnerScore - playerOneToWin.loserScore}`}</div>
      <hr />
      <div>Player Two</div>
      <div>{playerTwoToWin.steps}</div>
      <div>{`${playerTwoToWin.winnerScore} - ${playerTwoToWin.loserScore}`}</div>
      <div>{`${playerTwoToWin.winnerScore - playerTwoToWin.loserScore}`}</div>
    </div>
  )
}

export default Home
